### ISSUE TITLE
Are you going to publish this to atmosphere?

### ISSUE THREAD

**Issue by ryw** [gandev/meteor-server-eval#1]

**Comment by gandev** [comment]
Not sure yet, i think its nothing you should easily end up in production..

**Comment by emgee3** [comment]
I think some self-destruct code could be added into the isServer block, something like this should work:

```
Meteor.startup(function () {
  if (__meteor_runtime_config__) {
    if (__meteor_runtime_config__.ROOT_URL.indexOf('localhost') !== -1)
      return;
  }

  console.log("FATAL ERROR: METEOR-SERVER-EVAL MUST NOT RUN IN PRODUCTION");
  process.exit();
});
```

**Comment by gandev** [comment]
Thanks, i definitely consider this and i'm going to release it on
athmosphere when i have some things figured out in the package.

2013/11/6 emgee3 notifications@github.com

**Comment by gandev** [comment]
check out https://atmosphere.meteor.com/package/server-eval
